/*
DROP TABLE IF EXISTS player;
CREATE TABLE player (
   ID INTEGER NOT NULL,
   Name VARCHAR(255) NOT NULL,
   Nationality VARCHAR(255) NOT NULL,
   Birth_date TIMESTAMP,
   Titles INTEGER,
   PRIMARY KEY (ID)
);
*/
